#version 430 core


layout(location = 0, rgba32f) readonly uniform image2D testImage;

layout  (local_size_x  =  1)  in;

layout(std430, binding=0) readonly buffer Inp{
    float Input[];
};
layout(std430, binding=1) writeonly buffer Outp{
    float Output[];
};

uniform float multiplicator = 2.0;

void main(){
    float color = imageLoad(testImage, ivec2(1, gl_GlobalInvocationID.x)).x;
    Output[gl_GlobalInvocationID.x] = Input[gl_GlobalInvocationID.x] * multiplicator;

    //Output[gl_GlobalInvocationID.x] = color;
}